### PR TITLE
feat: add UnicodeCharacters module

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Review by cryogenian — CHANGES_REQUESTED** [review]
Could you please move constants out of record? There is no need in additional wrapper and its type IMO

**Comment by srghma** [comment]
done

**Comment by cryogenian** [comment]
Thank you very much! Please use unicode in code too 🙂 i.e. `::` -> `∷`

**Comment by srghma** [comment]
done

**Review by cryogenian — APPROVED** [review]
:100:

**Pull request merged**
